name: Front Deploy

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy frontend code to shared volume
      run: |
        rm -rf /deploy/talkpick-frontend/app*
        cp -r . /deploy/talkpick-frontend/app

    - name: Restart Docker
      run: |
        cd /deploy
        docker-compose up -d --build --force-recreate front
